### PR TITLE
Init_project

### PR DESCRIPTION
**Pull request by ngyihkai**
Ready

### CODE REVIEW

**Comment by ngyihkai** [comment]
Ready

**Comment by huongnt-2545** [comment]
conflicted

**Review by huongnt-2545 — COMMENTED** [review]
This pull request have 4 commits, you need to combine in 1
refs: https://stackoverflow.com/questions/35703556/what-does-it-mean-to-squash-commits-in-git

**Comment by ngyihkai** [comment]
Can I delete this repository and redo again because I had merged my chapter 3. Also this branch is closed

**Pull request closed without merging**
